language: php
php:
  - '5.6'
  - '7.0'
  - '7,1'
  - nightly
  - hhvm
install:
  - composer install --dev --no-interaction
script:
  - composer test
after_success:
  - travis_retry php vendor/bin/coveralls -v
